version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependendies..."
      - pip install  -r requirements.txt -t lib
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo "zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands: 
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name AWS-Lambda-GitHub-Latest --zip-file fileb://deployment_package.zip
      - echo "DONE!!"