version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
      - echo "Installing dependendies..."
      - pip install -r requirements.txt -t lib
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
      - echo "zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
    finally:
      - echo Executing Build Finally
  post_build:
    commands: 
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name LambdaGithubActions2 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
    finally:
      - echo Executing Post Build Finally